<a href="https://colab.research.google.com/github/AlejandraConB/ejercicio_tensorflow_basico/blob/main/ejercicio_tensorflow_basico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Guía detallada de uso de tensores en TensorFlow
##Requisitos previos: Python 3.x, tensorflow>=2.0, numpy
- Nota: En TensorFlow 2.x la ejecución es eager por defecto, lo que significa que las operaciones se evalúan inmediatamente.

###1) De listas / NumPy a tf.Tensor

In [5]:
!pip install --user tensorflow

In [6]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [8]:
import tensorflow as tf
import numpy as np


In [9]:
import numpy as np
import tensorflow as tf

# a) Desde un arreglo de NumPy (especificando dtype)
a = np.array([1, 2, 3], dtype=np.int32)

# b) Desde una lista de Python
b = [4, 5, 6]

# Convertimos a tensores
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)  # Inferirá dtype=int32

print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


###Explicación

- tf.convert_to_tensor convierte listas, arrays de NumPy u otros tensores a un tf.Tensor.
- El parámetro dtype controla el tipo de dato, por ejemplo tf.float32, tf.int32, etc.

In [1]:
import numpy as np

# Crear dos arreglos con los mismos valores pero diferente dtype
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
arr_float64 = np.array([1.0, 2.0, 3.0], dtype=np.float64)
arr_int8 = np.array([1, 2, 3], dtype=np.int8)


# Imprimir los arreglos y sus dtypes
print("Arreglo con dtype int32:")
print(arr_int32)
print("dtype:", arr_int32.dtype)
print("-" * 20)

print("Arreglo con dtype float64:")
print(arr_float64)
print("dtype:", arr_float64.dtype)
print("-" * 20)

print("Arreglo con dtype int8:")
print(arr_int8)
print("dtype:", arr_int8.dtype)
print("-" * 20)

# Mostrar el tamaño en bytes de cada elemento (esto puede variar ligeramente)
print(f"Tamaño de un elemento en arr_int32: {arr_int32.itemsize} bytes")
print(f"Tamaño de un elemento en arr_float64: {arr_float64.itemsize} bytes")
print(f"Tamaño de un elemento en arr_int8: {arr_int8.itemsize} bytes")

Arreglo con dtype int32:
[1 2 3]
dtype: int32
--------------------
Arreglo con dtype float64:
[1. 2. 3.]
dtype: float64
--------------------
Arreglo con dtype int8:
[1 2 3]
dtype: int8
--------------------
Tamaño de un elemento en arr_int32: 4 bytes
Tamaño de un elemento en arr_float64: 8 bytes
Tamaño de un elemento en arr_int8: 1 bytes


###Explicación

- Python es dinámicamente tipado y tiene gestión automática de memoria, y para las listas estándar de Python, no necesitas preocuparte por el tipo de datos de cada elemento de la misma manera.

- Sin embargo, bibliotecas como NumPy y TensorFlow operan a un nivel diferente al de las listas básicas de Python. Están diseñadas para manejar grandes cantidades de datos numéricos de manera muy eficiente, especialmente para cálculos científicos y de aprendizaje automático. Para lograr esta eficiencia, estas bibliotecas a menudo trabajan con bloques de memoria contiguos y optimizan las operaciones basándose en el tipo de datos de los elementos.